
FPS = 60

SCREEN_PROPORTION = (16, 9)
PROP_CONST = 70
SCREEN_SIZE = (PROP_CONST * SCREEN_PROPORTION[0], PROP_CONST * SCREEN_PROPORTION[1])

TILE_SIZE = 64

PADDLE_H = SCREEN_SIZE[1] / SCREEN_PROPORTION[1] * 2